// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package sqlc

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, org_id, task_id, uploader_id, filename, mime, size, storage_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, task_id, uploader_id, filename, mime, size, storage_key, created_at
`

type CreateAttachmentParams struct {
	ID         string
	OrgID      string
	TaskID     string
	UploaderID string
	Filename   string
	Mime       string
	Size       int64
	StorageKey string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.ID,
		arg.OrgID,
		arg.TaskID,
		arg.UploaderID,
		arg.Filename,
		arg.Mime,
		arg.Size,
		arg.StorageKey,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TaskID,
		&i.UploaderID,
		&i.Filename,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ? AND org_id = ?
`

type DeleteAttachmentParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.OrgID)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, org_id, task_id, uploader_id, filename, mime, size, storage_key, created_at
FROM attachments
WHERE id = ?
`

func (q *Queries) GetAttachment(ctx context.Context, id string) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TaskID,
		&i.UploaderID,
		&i.Filename,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentByKey = `-- name: GetAttachmentByKey :one
SELECT id, org_id, task_id, uploader_id, filename, mime, size, storage_key, created_at
FROM attachments
WHERE storage_key = ?
`

func (q *Queries) GetAttachmentByKey(ctx context.Context, storageKey string) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentByKey, storageKey)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TaskID,
		&i.UploaderID,
		&i.Filename,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByOrg = `-- name: ListAttachmentsByOrg :many
SELECT id, org_id, task_id, uploader_id, filename, mime, size, storage_key, created_at
FROM attachments
WHERE org_id = ?
ORDER BY created_at
`

func (q *Queries) ListAttachmentsByOrg(ctx context.Context, orgID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TaskID,
			&i.UploaderID,
			&i.Filename,
			&i.Mime,
			&i.Size,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByTask = `-- name: ListAttachmentsByTask :many
SELECT id, org_id, task_id, uploader_id, filename, mime, size, storage_key, created_at
FROM attachments
WHERE task_id = ?
ORDER BY created_at
`

func (q *Queries) ListAttachmentsByTask(ctx context.Context, taskID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TaskID,
			&i.UploaderID,
			&i.Filename,
			&i.Mime,
			&i.Size,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
