// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data_export.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET email = '', name = 'Former member', avatar_url = '', deleted_at = strftime('%Y-%m-%dT%H:%M:%S.000Z', 'now')
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserApiKeys = `-- name: DeleteUserApiKeys :exec
DELETE FROM api_keys WHERE user_id = ?
`

func (q *Queries) DeleteUserApiKeys(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserApiKeys, userID)
	return err
}

const deleteUserIdentities = `-- name: DeleteUserIdentities :exec
DELETE FROM identities WHERE user_id = ?
`

func (q *Queries) DeleteUserIdentities(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserIdentities, userID)
	return err
}

const deleteUserMemberships = `-- name: DeleteUserMemberships :exec
DELETE FROM memberships WHERE actor_id = ? AND actor_type = 'user'
`

func (q *Queries) DeleteUserMemberships(ctx context.Context, actorID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserMemberships, actorID)
	return err
}

const deleteUserNotifications = `-- name: DeleteUserNotifications :exec
DELETE FROM notifications WHERE user_id = ?
`

func (q *Queries) DeleteUserNotifications(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserNotifications, userID)
	return err
}

const deleteUserSavedFilters = `-- name: DeleteUserSavedFilters :exec
DELETE FROM saved_filters WHERE created_by = ?
`

func (q *Queries) DeleteUserSavedFilters(ctx context.Context, createdBy string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSavedFilters, createdBy)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const listOrgMemberships = `-- name: ListOrgMemberships :many
SELECT id, org_id, actor_id, actor_type, resource_type, resource_id, role_id, created_at
FROM memberships
WHERE org_id = ?
`

func (q *Queries) ListOrgMemberships(ctx context.Context, orgID string) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMemberships, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.ActorType,
			&i.ResourceType,
			&i.ResourceID,
			&i.RoleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgProjects = `-- name: ListOrgProjects :many
SELECT id, org_id, team_id, name, key, context, visibility, archived, next_task_num, created_at
FROM projects
WHERE org_id = ?
`

func (q *Queries) ListOrgProjects(ctx context.Context, orgID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listOrgProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.Name,
			&i.Key,
			&i.Context,
			&i.Visibility,
			&i.Archived,
			&i.NextTaskNum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgRoles = `-- name: ListOrgRoles :many
SELECT id, org_id, name, is_system, grants_json, created_at
FROM roles
WHERE org_id = ?
`

func (q *Queries) ListOrgRoles(ctx context.Context, orgID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listOrgRoles, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.IsSystem,
			&i.GrantsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgSecrets2 = `-- name: ListOrgSecrets2 :many
SELECT id, org_id, key, ciphertext, created_at
FROM org_secrets
WHERE org_id = ?
`

func (q *Queries) ListOrgSecrets2(ctx context.Context, orgID string) ([]OrgSecret, error) {
	rows, err := q.db.QueryContext(ctx, listOrgSecrets2, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgSecret
	for rows.Next() {
		var i OrgSecret
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgTeams = `-- name: ListOrgTeams :many
SELECT id, org_id, name, slug, context, visibility, created_at
FROM teams
WHERE org_id = ?
`

func (q *Queries) ListOrgTeams(ctx context.Context, orgID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listOrgTeams, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Context,
			&i.Visibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserApiKeys = `-- name: ListUserApiKeys :many
SELECT id, user_id, org_id, name, prefix, scope_json, last_used_at, created_at, revoked_at
FROM api_keys
WHERE user_id = ?
`

type ListUserApiKeysRow struct {
	ID         string
	UserID     string
	OrgID      string
	Name       string
	Prefix     string
	ScopeJson  string
	LastUsedAt sql.NullString
	CreatedAt  string
	RevokedAt  sql.NullString
}

func (q *Queries) ListUserApiKeys(ctx context.Context, userID string) ([]ListUserApiKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserApiKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserApiKeysRow
	for rows.Next() {
		var i ListUserApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.ScopeJson,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserComments = `-- name: ListUserComments :many
SELECT id, task_id, project_id, author_id, body, created_at, updated_at
FROM comments
WHERE author_id = ?
`

type ListUserCommentsRow struct {
	ID        string
	TaskID    string
	ProjectID string
	AuthorID  string
	Body      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) ListUserComments(ctx context.Context, authorID string) ([]ListUserCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserComments, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCommentsRow
	for rows.Next() {
		var i ListUserCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ProjectID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIdentities = `-- name: ListUserIdentities :many
SELECT id, user_id, provider, subject, email
FROM identities
WHERE user_id = ?
`

type ListUserIdentitiesRow struct {
	ID       string
	UserID   string
	Provider string
	Subject  string
	Email    string
}

func (q *Queries) ListUserIdentities(ctx context.Context, userID string) ([]ListUserIdentitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserIdentitiesRow
	for rows.Next() {
		var i ListUserIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT m.id, m.org_id, m.actor_id, m.actor_type, m.resource_type, m.resource_id, m.role_id, m.created_at, o.name as org_name
FROM memberships m
JOIN orgs o ON o.id = m.org_id
WHERE m.actor_id = ? AND m.actor_type = 'user'
`

type ListUserMembershipsRow struct {
	ID           string
	OrgID        string
	ActorID      string
	ActorType    string
	ResourceType string
	ResourceID   string
	RoleID       sql.NullString
	CreatedAt    string
	OrgName      string
}

func (q *Queries) ListUserMemberships(ctx context.Context, actorID string) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserMemberships, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsRow
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.ActorType,
			&i.ResourceType,
			&i.ResourceID,
			&i.RoleID,
			&i.CreatedAt,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, org_id, user_id, event_name, subject_id, title, body, grouping_key, created_at, read_at
FROM notifications
WHERE user_id = ?
`

func (q *Queries) ListUserNotifications(ctx context.Context, userID string) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.EventName,
			&i.SubjectID,
			&i.Title,
			&i.Body,
			&i.GroupingKey,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSavedFilters = `-- name: ListUserSavedFilters :many
SELECT id, project_id, name, query_json, pinned, created_by, created_at, updated_at
FROM saved_filters
WHERE created_by = ?
`

func (q *Queries) ListUserSavedFilters(ctx context.Context, createdBy string) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listUserSavedFilters, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedFilter
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.QueryJson,
			&i.Pinned,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT token_hash, user_id, ip, ua, created_at, last_seen_at, expires_at
FROM sessions
WHERE user_id = ?
`

func (q *Queries) ListUserSessions(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TokenHash,
			&i.UserID,
			&i.Ip,
			&i.Ua,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTaskActivity = `-- name: ListUserTaskActivity :many
SELECT id, task_id, project_id, actor_id, actor_type, action, detail_json, created_at
FROM task_activity
WHERE actor_id = ? AND actor_type = 'user'
`

type ListUserTaskActivityRow struct {
	ID         string
	TaskID     string
	ProjectID  string
	ActorID    string
	ActorType  string
	Action     string
	DetailJson string
	CreatedAt  string
}

func (q *Queries) ListUserTaskActivity(ctx context.Context, actorID string) ([]ListUserTaskActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserTaskActivity, actorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTaskActivityRow
	for rows.Next() {
		var i ListUserTaskActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ProjectID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.DetailJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTaskAssignments = `-- name: ListUserTaskAssignments :many
SELECT task_id, project_id, user_id
FROM task_assignees
WHERE user_id = ?
`

func (q *Queries) ListUserTaskAssignments(ctx context.Context, userID string) ([]TaskAssignee, error) {
	rows, err := q.db.QueryContext(ctx, listUserTaskAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskAssignee
	for rows.Next() {
		var i TaskAssignee
		if err := rows.Scan(&i.TaskID, &i.ProjectID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWatchers = `-- name: ListUserWatchers :many
SELECT task_id, project_id, user_id
FROM task_watchers
WHERE user_id = ?
`

func (q *Queries) ListUserWatchers(ctx context.Context, userID string) ([]TaskWatcher, error) {
	rows, err := q.db.QueryContext(ctx, listUserWatchers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskWatcher
	for rows.Next() {
		var i TaskWatcher
		if err := rows.Scan(&i.TaskID, &i.ProjectID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reattributeComments = `-- name: ReattributeComments :exec
UPDATE comments SET author_id = 'ffffffffffffffffffffffffffffffff', deleted_by = ?
WHERE author_id = ?
`

type ReattributeCommentsParams struct {
	DeletedBy string
	AuthorID  string
}

func (q *Queries) ReattributeComments(ctx context.Context, arg ReattributeCommentsParams) error {
	_, err := q.db.ExecContext(ctx, reattributeComments, arg.DeletedBy, arg.AuthorID)
	return err
}

const reattributeTaskActivity = `-- name: ReattributeTaskActivity :exec
UPDATE task_activity SET actor_id = 'ffffffffffffffffffffffffffffffff', deleted_by = ?
WHERE actor_id = ? AND actor_type = 'user'
`

type ReattributeTaskActivityParams struct {
	DeletedBy string
	ActorID   string
}

func (q *Queries) ReattributeTaskActivity(ctx context.Context, arg ReattributeTaskActivityParams) error {
	_, err := q.db.ExecContext(ctx, reattributeTaskActivity, arg.DeletedBy, arg.ActorID)
	return err
}

const reattributeTaskAssignees = `-- name: ReattributeTaskAssignees :exec
DELETE FROM task_assignees WHERE user_id = ?
`

func (q *Queries) ReattributeTaskAssignees(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, reattributeTaskAssignees, userID)
	return err
}

const reattributeTaskWatchers = `-- name: ReattributeTaskWatchers :exec
DELETE FROM task_watchers WHERE user_id = ?
`

func (q *Queries) ReattributeTaskWatchers(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, reattributeTaskWatchers, userID)
	return err
}
