// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createGithubLink = `-- name: CreateGithubLink :one
INSERT INTO github_links (id, project_id, kind, key, key_num, ref, state, task_id, url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, kind, key, key_num, ref, state, task_id, url, created_at, updated_at
`

type CreateGithubLinkParams struct {
	ID        string
	ProjectID string
	Kind      string
	Key       string
	KeyNum    int64
	Ref       string
	State     string
	TaskID    sql.NullString
	Url       string
}

func (q *Queries) CreateGithubLink(ctx context.Context, arg CreateGithubLinkParams) (GithubLink, error) {
	row := q.db.QueryRowContext(ctx, createGithubLink,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Key,
		arg.KeyNum,
		arg.Ref,
		arg.State,
		arg.TaskID,
		arg.Url,
	)
	var i GithubLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Key,
		&i.KeyNum,
		&i.Ref,
		&i.State,
		&i.TaskID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectGithub = `-- name: DeleteProjectGithub :exec
DELETE FROM project_github
WHERE repo = ?
`

func (q *Queries) DeleteProjectGithub(ctx context.Context, repo string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectGithub, repo)
	return err
}

const findProjectGithubByProject = `-- name: FindProjectGithubByProject :one
SELECT id, project_id, repo, transitions, webhook_secret, enabled, created_at, updated_at
FROM project_github
WHERE project_id = ?
`

func (q *Queries) FindProjectGithubByProject(ctx context.Context, projectID string) (ProjectGithub, error) {
	row := q.db.QueryRowContext(ctx, findProjectGithubByProject, projectID)
	var i ProjectGithub
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Repo,
		&i.Transitions,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProjectGithubByRepo = `-- name: FindProjectGithubByRepo :one
SELECT id, project_id, repo, transitions, webhook_secret, enabled, created_at, updated_at
FROM project_github
WHERE repo = ?
`

func (q *Queries) FindProjectGithubByRepo(ctx context.Context, repo string) (ProjectGithub, error) {
	row := q.db.QueryRowContext(ctx, findProjectGithubByRepo, repo)
	var i ProjectGithub
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Repo,
		&i.Transitions,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGithubLinksByProject = `-- name: ListGithubLinksByProject :many
SELECT id, project_id, kind, key, key_num, ref, state, task_id, url, created_at, updated_at
FROM github_links
WHERE project_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListGithubLinksByProject(ctx context.Context, projectID string) ([]GithubLink, error) {
	rows, err := q.db.QueryContext(ctx, listGithubLinksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubLink
	for rows.Next() {
		var i GithubLink
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Key,
			&i.KeyNum,
			&i.Ref,
			&i.State,
			&i.TaskID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubLinksByTask = `-- name: ListGithubLinksByTask :many
SELECT id, project_id, kind, key, key_num, ref, state, task_id, url, created_at, updated_at
FROM github_links
WHERE task_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListGithubLinksByTask(ctx context.Context, taskID sql.NullString) ([]GithubLink, error) {
	rows, err := q.db.QueryContext(ctx, listGithubLinksByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubLink
	for rows.Next() {
		var i GithubLink
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Key,
			&i.KeyNum,
			&i.Ref,
			&i.State,
			&i.TaskID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectGithubByOrg = `-- name: ListProjectGithubByOrg :many
SELECT pg.id, pg.project_id, pg.repo, pg.transitions, pg.webhook_secret, pg.enabled, pg.created_at, pg.updated_at
FROM project_github pg
JOIN projects p ON p.id = pg.project_id
WHERE p.org_id = ?
ORDER BY pg.repo ASC
`

func (q *Queries) ListProjectGithubByOrg(ctx context.Context, orgID string) ([]ProjectGithub, error) {
	rows, err := q.db.QueryContext(ctx, listProjectGithubByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectGithub
	for rows.Next() {
		var i ProjectGithub
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Repo,
			&i.Transitions,
			&i.WebhookSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGithubLink = `-- name: UpsertGithubLink :one
INSERT INTO github_links (id, project_id, kind, key, key_num, ref, state, task_id, url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id, kind, key, key_num, ref) DO UPDATE SET
    state = excluded.state,
    task_id = excluded.task_id,
    url = excluded.url,
    updated_at = excluded.updated_at
RETURNING id, project_id, kind, key, key_num, ref, state, task_id, url, created_at, updated_at
`

type UpsertGithubLinkParams struct {
	ID        string
	ProjectID string
	Kind      string
	Key       string
	KeyNum    int64
	Ref       string
	State     string
	TaskID    sql.NullString
	Url       string
}

// One row per (kind, key, key_num, ref); update state/task/url on re-delivery.
func (q *Queries) UpsertGithubLink(ctx context.Context, arg UpsertGithubLinkParams) (GithubLink, error) {
	row := q.db.QueryRowContext(ctx, upsertGithubLink,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Key,
		arg.KeyNum,
		arg.Ref,
		arg.State,
		arg.TaskID,
		arg.Url,
	)
	var i GithubLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Key,
		&i.KeyNum,
		&i.Ref,
		&i.State,
		&i.TaskID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectGithub = `-- name: UpsertProjectGithub :one
INSERT INTO project_github (id, project_id, repo, transitions, webhook_secret, enabled, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(repo) DO UPDATE SET
    project_id = excluded.project_id,
    transitions = excluded.transitions,
    webhook_secret = excluded.webhook_secret,
    enabled = excluded.enabled,
    updated_at = excluded.updated_at
RETURNING id, project_id, repo, transitions, webhook_secret, enabled, created_at, updated_at
`

type UpsertProjectGithubParams struct {
	ID            string
	ProjectID     string
	Repo          string
	Transitions   string
	WebhookSecret string
	Enabled       int64
	UpdatedAt     string
}

// Config row is keyed by repo (unique); create-or-update keeps a single row.
func (q *Queries) UpsertProjectGithub(ctx context.Context, arg UpsertProjectGithubParams) (ProjectGithub, error) {
	row := q.db.QueryRowContext(ctx, upsertProjectGithub,
		arg.ID,
		arg.ProjectID,
		arg.Repo,
		arg.Transitions,
		arg.WebhookSecret,
		arg.Enabled,
		arg.UpdatedAt,
	)
	var i ProjectGithub
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Repo,
		&i.Transitions,
		&i.WebhookSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
