// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlc

import (
	"context"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_keys (key, actor, action, result_json, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateIdempotencyKeyParams struct {
	Key        string
	Actor      string
	Action     string
	ResultJson string
	CreatedAt  string
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, createIdempotencyKey,
		arg.Key,
		arg.Actor,
		arg.Action,
		arg.ResultJson,
		arg.CreatedAt,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, actor, action, result_json, created_at
FROM idempotency_keys
WHERE key = ?
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Actor,
		&i.Action,
		&i.ResultJson,
		&i.CreatedAt,
	)
	return i, err
}
