// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idp_mappings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createIdPGroupMapping = `-- name: CreateIdPGroupMapping :exec

INSERT INTO idp_group_mappings (id, org_id, provider_id, group_value, role_id, resource_type, resource_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateIdPGroupMappingParams struct {
	ID           string
	OrgID        string
	ProviderID   sql.NullString
	GroupValue   string
	RoleID       string
	ResourceType string
	ResourceID   string
}

// IdP group -> role mappings and JIT settings (WU-608, SPEC s7.5). Every
// query binds org_id.
func (q *Queries) CreateIdPGroupMapping(ctx context.Context, arg CreateIdPGroupMappingParams) error {
	_, err := q.db.ExecContext(ctx, createIdPGroupMapping,
		arg.ID,
		arg.OrgID,
		arg.ProviderID,
		arg.GroupValue,
		arg.RoleID,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const createSourcedMembership = `-- name: CreateSourcedMembership :exec
INSERT INTO memberships (id, org_id, actor_id, actor_type, resource_type, resource_id, role_id, source)
VALUES (?, ?, ?, 'user', ?, ?, ?, ?)
`

type CreateSourcedMembershipParams struct {
	ID           string
	OrgID        string
	ActorID      string
	ResourceType string
	ResourceID   string
	RoleID       sql.NullString
	Source       string
}

func (q *Queries) CreateSourcedMembership(ctx context.Context, arg CreateSourcedMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createSourcedMembership,
		arg.ID,
		arg.OrgID,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.RoleID,
		arg.Source,
	)
	return err
}

const deleteIdPGroupMapping = `-- name: DeleteIdPGroupMapping :execrows
DELETE FROM idp_group_mappings
WHERE id = ? AND org_id = ?
`

type DeleteIdPGroupMappingParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteIdPGroupMapping(ctx context.Context, arg DeleteIdPGroupMappingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIdPGroupMapping, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteIdPMembership = `-- name: DeleteIdPMembership :execrows
DELETE FROM memberships
WHERE id = ? AND org_id = ? AND source = 'idp'
`

type DeleteIdPMembershipParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteIdPMembership(ctx context.Context, arg DeleteIdPMembershipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIdPMembership, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findRoleForOrg = `-- name: FindRoleForOrg :one
SELECT id, org_id, name, is_system, grants_json, created_at
FROM roles
WHERE id = ?1
  AND (org_id = ?2 OR (org_id = '00000000000000000000000000000000' AND is_system = 1))
`

type FindRoleForOrgParams struct {
	ID    string
	OrgID string
}

// A role usable in org_id: one the org owns, or a seeded system role (held
// by the platform org and shared by every org).
func (q *Queries) FindRoleForOrg(ctx context.Context, arg FindRoleForOrgParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleForOrg, arg.ID, arg.OrgID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsSystem,
		&i.GrantsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listIdPGroupMappings = `-- name: ListIdPGroupMappings :many
SELECT id, org_id, provider_id, group_value, role_id, resource_type, resource_id, created_at FROM idp_group_mappings
WHERE org_id = ?
ORDER BY group_value, created_at, id
`

func (q *Queries) ListIdPGroupMappings(ctx context.Context, orgID string) ([]IdpGroupMapping, error) {
	rows, err := q.db.QueryContext(ctx, listIdPGroupMappings, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdpGroupMapping
	for rows.Next() {
		var i IdpGroupMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProviderID,
			&i.GroupValue,
			&i.RoleID,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdPGroupMappingsForProvider = `-- name: ListIdPGroupMappingsForProvider :many
SELECT id, org_id, provider_id, group_value, role_id, resource_type, resource_id, created_at FROM idp_group_mappings
WHERE org_id = ?1
  AND (provider_id IS NULL OR provider_id = ?2)
ORDER BY created_at, id
`

type ListIdPGroupMappingsForProviderParams struct {
	OrgID      string
	ProviderID sql.NullString
}

// Mappings that apply to sign-ins through provider_id: its own plus the
// org-wide ones (provider_id NULL). Oldest first: when two mappings target
// the same resource with different roles, the oldest wins.
func (q *Queries) ListIdPGroupMappingsForProvider(ctx context.Context, arg ListIdPGroupMappingsForProviderParams) ([]IdpGroupMapping, error) {
	rows, err := q.db.QueryContext(ctx, listIdPGroupMappingsForProvider, arg.OrgID, arg.ProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdpGroupMapping
	for rows.Next() {
		var i IdpGroupMapping
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProviderID,
			&i.GroupValue,
			&i.RoleID,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgSSOProvisioning = `-- name: SetOrgSSOProvisioning :exec
INSERT INTO org_sso_settings (org_id, jit_enabled, jit_default_role_id, group_claim, group_sync, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT (org_id) DO UPDATE SET
    jit_enabled         = excluded.jit_enabled,
    jit_default_role_id = excluded.jit_default_role_id,
    group_claim         = excluded.group_claim,
    group_sync          = excluded.group_sync,
    updated_at          = excluded.updated_at
`

type SetOrgSSOProvisioningParams struct {
	OrgID            string
	JitEnabled       int64
	JitDefaultRoleID sql.NullString
	GroupClaim       string
	GroupSync        int64
}

func (q *Queries) SetOrgSSOProvisioning(ctx context.Context, arg SetOrgSSOProvisioningParams) error {
	_, err := q.db.ExecContext(ctx, setOrgSSOProvisioning,
		arg.OrgID,
		arg.JitEnabled,
		arg.JitDefaultRoleID,
		arg.GroupClaim,
		arg.GroupSync,
	)
	return err
}

const updateIdPMembershipRole = `-- name: UpdateIdPMembershipRole :execrows
UPDATE memberships SET role_id = ?
WHERE id = ? AND org_id = ? AND source = 'idp'
`

type UpdateIdPMembershipRoleParams struct {
	RoleID sql.NullString
	ID     string
	OrgID  string
}

func (q *Queries) UpdateIdPMembershipRole(ctx context.Context, arg UpdateIdPMembershipRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIdPMembershipRole, arg.RoleID, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
