// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type AuditLog struct {
	ID         string
	OrgID      sql.NullString
	ActorType  string
	ActorID    string
	Action     string
	Subject    string
	DetailJson string
	Ip         string
	CreatedAt  string
}

type IdempotencyKey struct {
	Key        string
	Actor      string
	Action     string
	ResultJson string
	CreatedAt  string
}

type Identity struct {
	ID       string
	UserID   string
	Provider string
	Subject  string
	Email    string
	TokenEnc []byte
}

type PlatformSetting struct {
	ID            int64
	Context       string
	BootstrapDone int64
	SettingsJson  string
}

type Session struct {
	TokenHash  string
	UserID     string
	Ip         string
	Ua         string
	CreatedAt  string
	LastSeenAt string
	ExpiresAt  string
}

type User struct {
	ID        string
	Email     string
	Name      string
	AvatarUrl string
	Theme     string
	Timezone  string
	CreatedAt string
	DeletedAt sql.NullString
}
