// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_sso.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createOrgAuthProvider = `-- name: CreateOrgAuthProvider :exec
INSERT INTO auth_providers (id, org_id, kind, preset, display_name, enabled, managed_by, issuer,
                            client_id, client_secret_enc, scopes, claim_map_json,
                            trust_email, allow_signup, allowed_tenants_json, position)
VALUES (?, ?, ?, ?, ?, ?, 'ui', ?, ?, ?, ?, ?, ?, 0, ?, ?)
`

type CreateOrgAuthProviderParams struct {
	ID                 string
	OrgID              sql.NullString
	Kind               string
	Preset             string
	DisplayName        string
	Enabled            int64
	Issuer             string
	ClientID           string
	ClientSecretEnc    string
	Scopes             string
	ClaimMapJson       string
	TrustEmail         int64
	AllowedTenantsJson string
	Position           int64
}

func (q *Queries) CreateOrgAuthProvider(ctx context.Context, arg CreateOrgAuthProviderParams) error {
	_, err := q.db.ExecContext(ctx, createOrgAuthProvider,
		arg.ID,
		arg.OrgID,
		arg.Kind,
		arg.Preset,
		arg.DisplayName,
		arg.Enabled,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.Scopes,
		arg.ClaimMapJson,
		arg.TrustEmail,
		arg.AllowedTenantsJson,
		arg.Position,
	)
	return err
}

const deleteOrgAuthProvider = `-- name: DeleteOrgAuthProvider :execrows
DELETE FROM auth_providers
WHERE id = ? AND org_id = ? AND managed_by = 'ui'
`

type DeleteOrgAuthProviderParams struct {
	ID    string
	OrgID sql.NullString
}

func (q *Queries) DeleteOrgAuthProvider(ctx context.Context, arg DeleteOrgAuthProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrgAuthProvider, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findProjectOrg = `-- name: FindProjectOrg :one
SELECT org_id FROM projects
WHERE id = ?
`

// Maps a project id to its org for the SSO gate on /app/project/{id}
// routes, which carry no org id.
func (q *Queries) FindProjectOrg(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, findProjectOrg, id)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const getOrgAuthProvider = `-- name: GetOrgAuthProvider :one
SELECT id, org_id, kind, preset, display_name, enabled, managed_by, issuer, client_id, client_secret_enc, scopes, claim_map_json, trust_email, allow_signup, allowed_tenants_json, saml_metadata_url, saml_metadata_xml, sp_key_enc, sp_cert, position, created_at, updated_at FROM auth_providers
WHERE id = ? AND org_id = ?
`

type GetOrgAuthProviderParams struct {
	ID    string
	OrgID sql.NullString
}

func (q *Queries) GetOrgAuthProvider(ctx context.Context, arg GetOrgAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRowContext(ctx, getOrgAuthProvider, arg.ID, arg.OrgID)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Preset,
		&i.DisplayName,
		&i.Enabled,
		&i.ManagedBy,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.Scopes,
		&i.ClaimMapJson,
		&i.TrustEmail,
		&i.AllowSignup,
		&i.AllowedTenantsJson,
		&i.SamlMetadataUrl,
		&i.SamlMetadataXml,
		&i.SpKeyEnc,
		&i.SpCert,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgSSOSettings = `-- name: GetOrgSSOSettings :one
SELECT org_id, enforce_sso, jit_enabled, jit_default_role_id, group_claim, group_sync, updated_at FROM org_sso_settings
WHERE org_id = ?
`

func (q *Queries) GetOrgSSOSettings(ctx context.Context, orgID string) (OrgSsoSetting, error) {
	row := q.db.QueryRowContext(ctx, getOrgSSOSettings, orgID)
	var i OrgSsoSetting
	err := row.Scan(
		&i.OrgID,
		&i.EnforceSso,
		&i.JitEnabled,
		&i.JitDefaultRoleID,
		&i.GroupClaim,
		&i.GroupSync,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledOrgAuthProviderIDs = `-- name: ListEnabledOrgAuthProviderIDs :many
SELECT id FROM auth_providers
WHERE org_id = ? AND enabled = 1
ORDER BY position, id
`

func (q *Queries) ListEnabledOrgAuthProviderIDs(ctx context.Context, orgID sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledOrgAuthProviderIDs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgAuthProviders = `-- name: ListOrgAuthProviders :many

SELECT p.id, p.kind, p.preset, p.display_name, p.enabled, p.managed_by, p.issuer,
       p.client_id, CAST(p.client_secret_enc <> '' AS INTEGER) AS has_secret,
       p.scopes, p.claim_map_json, p.trust_email, p.allow_signup,
       p.allowed_tenants_json, p.position, p.created_at, p.updated_at,
       CAST((SELECT COUNT(*) FROM identities i WHERE i.provider = p.id) AS INTEGER) AS identity_count
FROM auth_providers p
WHERE p.org_id = ?
ORDER BY p.position, p.id
`

type ListOrgAuthProvidersRow struct {
	ID                 string
	Kind               string
	Preset             string
	DisplayName        string
	Enabled            int64
	ManagedBy          string
	Issuer             string
	ClientID           string
	HasSecret          int64
	Scopes             string
	ClaimMapJson       string
	TrustEmail         int64
	AllowSignup        int64
	AllowedTenantsJson string
	Position           int64
	CreatedAt          string
	UpdatedAt          string
	IdentityCount      int64
}

// Organisation SSO (WU-607, SPEC s7.4): org-owned sign-in providers and the
// per-org SSO settings. Every query binds org_id. auth_providers itself is not
// in check-scope's tenant list (nullable org_id), so these queries pin
// org_id = ? by hand; managed_by is always 'ui' for org rows.
// Omits client_secret_enc: callers only learn whether a secret is set.
func (q *Queries) ListOrgAuthProviders(ctx context.Context, orgID sql.NullString) ([]ListOrgAuthProvidersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgAuthProviders, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgAuthProvidersRow
	for rows.Next() {
		var i ListOrgAuthProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Preset,
			&i.DisplayName,
			&i.Enabled,
			&i.ManagedBy,
			&i.Issuer,
			&i.ClientID,
			&i.HasSecret,
			&i.Scopes,
			&i.ClaimMapJson,
			&i.TrustEmail,
			&i.AllowSignup,
			&i.AllowedTenantsJson,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrgAuthProviderPosition = `-- name: NextOrgAuthProviderPosition :one
SELECT CAST(COALESCE(MAX(position), 0) + 10 AS INTEGER) FROM auth_providers
WHERE org_id = ?
`

func (q *Queries) NextOrgAuthProviderPosition(ctx context.Context, orgID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextOrgAuthProviderPosition, orgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setOrgAuthProviderEnabled = `-- name: SetOrgAuthProviderEnabled :execrows
UPDATE auth_providers
SET enabled = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND org_id = ? AND managed_by = 'ui'
`

type SetOrgAuthProviderEnabledParams struct {
	Enabled int64
	ID      string
	OrgID   sql.NullString
}

func (q *Queries) SetOrgAuthProviderEnabled(ctx context.Context, arg SetOrgAuthProviderEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setOrgAuthProviderEnabled, arg.Enabled, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setOrgSSOEnforce = `-- name: SetOrgSSOEnforce :exec
INSERT INTO org_sso_settings (org_id, enforce_sso, updated_at)
VALUES (?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
ON CONFLICT (org_id) DO UPDATE SET
    enforce_sso = excluded.enforce_sso,
    updated_at  = excluded.updated_at
`

type SetOrgSSOEnforceParams struct {
	OrgID      string
	EnforceSso int64
}

func (q *Queries) SetOrgSSOEnforce(ctx context.Context, arg SetOrgSSOEnforceParams) error {
	_, err := q.db.ExecContext(ctx, setOrgSSOEnforce, arg.OrgID, arg.EnforceSso)
	return err
}

const updateOrgAuthProvider = `-- name: UpdateOrgAuthProvider :execrows
UPDATE auth_providers
SET preset               = ?,
    display_name         = ?,
    issuer               = ?,
    client_id            = ?,
    client_secret_enc    = ?,
    scopes               = ?,
    claim_map_json       = ?,
    trust_email          = ?,
    allow_signup         = 0,
    allowed_tenants_json = ?,
    position             = ?,
    updated_at           = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND org_id = ? AND managed_by = 'ui'
`

type UpdateOrgAuthProviderParams struct {
	Preset             string
	DisplayName        string
	Issuer             string
	ClientID           string
	ClientSecretEnc    string
	Scopes             string
	ClaimMapJson       string
	TrustEmail         int64
	AllowedTenantsJson string
	Position           int64
	ID                 string
	OrgID              sql.NullString
}

// allow_signup is always 0 for org-owned providers.
func (q *Queries) UpdateOrgAuthProvider(ctx context.Context, arg UpdateOrgAuthProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOrgAuthProvider,
		arg.Preset,
		arg.DisplayName,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.Scopes,
		arg.ClaimMapJson,
		arg.TrustEmail,
		arg.AllowedTenantsJson,
		arg.Position,
		arg.ID,
		arg.OrgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
