// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, org_id, name, is_system, grants_json)
VALUES (?, ?, ?, ?, ?)
RETURNING id, org_id, name, is_system, grants_json, created_at
`

type CreateRoleParams struct {
	ID         string
	OrgID      string
	Name       string
	IsSystem   int64
	GrantsJson string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.IsSystem,
		arg.GrantsJson,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsSystem,
		&i.GrantsJson,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = ? AND org_id = ?
`

type DeleteRoleParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRole, arg.ID, arg.OrgID)
	return err
}

const findRoleByID = `-- name: FindRoleByID :one
SELECT id, org_id, name, is_system, grants_json, created_at
FROM roles
WHERE id = ? AND org_id = ?
`

type FindRoleByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) FindRoleByID(ctx context.Context, arg FindRoleByIDParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleByID, arg.ID, arg.OrgID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsSystem,
		&i.GrantsJson,
		&i.CreatedAt,
	)
	return i, err
}

const findRoleByOrgAndName = `-- name: FindRoleByOrgAndName :one
SELECT id, org_id, name, is_system, grants_json, created_at
FROM roles
WHERE org_id = ? AND name = ?
`

type FindRoleByOrgAndNameParams struct {
	OrgID string
	Name  string
}

func (q *Queries) FindRoleByOrgAndName(ctx context.Context, arg FindRoleByOrgAndNameParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleByOrgAndName, arg.OrgID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsSystem,
		&i.GrantsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listRolesByOrg = `-- name: ListRolesByOrg :many
SELECT id, org_id, name, is_system, grants_json, created_at
FROM roles
WHERE org_id = ?
ORDER BY name
`

func (q *Queries) ListRolesByOrg(ctx context.Context, orgID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.IsSystem,
			&i.GrantsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = ?, grants_json = ?
WHERE id = ? AND org_id = ?
RETURNING id, org_id, name, is_system, grants_json, created_at
`

type UpdateRoleParams struct {
	Name       string
	GrantsJson string
	ID         string
	OrgID      string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole,
		arg.Name,
		arg.GrantsJson,
		arg.ID,
		arg.OrgID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsSystem,
		&i.GrantsJson,
		&i.CreatedAt,
	)
	return i, err
}
