// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_triggers.sql

package sqlc

import (
	"context"
)

const createScheduledTrigger = `-- name: CreateScheduledTrigger :one
INSERT INTO scheduled_triggers (id, org_id, project_id, agent_id, cron_expr, prompt, next_at, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, project_id, agent_id, cron_expr, prompt, next_at, enabled, created_at, updated_at
`

type CreateScheduledTriggerParams struct {
	ID        string
	OrgID     string
	ProjectID string
	AgentID   string
	CronExpr  string
	Prompt    string
	NextAt    string
	Enabled   int64
}

func (q *Queries) CreateScheduledTrigger(ctx context.Context, arg CreateScheduledTriggerParams) (ScheduledTrigger, error) {
	row := q.db.QueryRowContext(ctx, createScheduledTrigger,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.AgentID,
		arg.CronExpr,
		arg.Prompt,
		arg.NextAt,
		arg.Enabled,
	)
	var i ScheduledTrigger
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.CronExpr,
		&i.Prompt,
		&i.NextAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduledTrigger = `-- name: DeleteScheduledTrigger :exec
DELETE FROM scheduled_triggers
WHERE id = ? AND org_id = ?
`

type DeleteScheduledTriggerParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteScheduledTrigger(ctx context.Context, arg DeleteScheduledTriggerParams) error {
	_, err := q.db.ExecContext(ctx, deleteScheduledTrigger, arg.ID, arg.OrgID)
	return err
}

const findScheduledTriggerByID = `-- name: FindScheduledTriggerByID :one
SELECT id, org_id, project_id, agent_id, cron_expr, prompt, next_at, enabled, created_at, updated_at
FROM scheduled_triggers
WHERE id = ? AND org_id = ?
`

type FindScheduledTriggerByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) FindScheduledTriggerByID(ctx context.Context, arg FindScheduledTriggerByIDParams) (ScheduledTrigger, error) {
	row := q.db.QueryRowContext(ctx, findScheduledTriggerByID, arg.ID, arg.OrgID)
	var i ScheduledTrigger
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.CronExpr,
		&i.Prompt,
		&i.NextAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueScheduledTriggers = `-- name: ListDueScheduledTriggers :many
SELECT st.id, st.org_id, st.project_id, st.agent_id, st.cron_expr, st.prompt, st.next_at, st.enabled, st.created_at, st.updated_at
FROM scheduled_triggers st
JOIN projects p ON p.id = st.project_id AND p.org_id = st.org_id
WHERE st.enabled = 1 AND st.next_at != '' AND st.next_at <= ?
ORDER BY st.next_at ASC
`

// Fired by the scheduler (WU-309): enabled triggers whose next_at is at or
// before the given reference time. The JOIN to projects keeps the project's
// org in scope and lets the scheduler skip paused projects via the caller.
func (q *Queries) ListDueScheduledTriggers(ctx context.Context, nextAt string) ([]ScheduledTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listDueScheduledTriggers, nextAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTrigger
	for rows.Next() {
		var i ScheduledTrigger
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.CronExpr,
			&i.Prompt,
			&i.NextAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTriggersByProject = `-- name: ListScheduledTriggersByProject :many
SELECT id, org_id, project_id, agent_id, cron_expr, prompt, next_at, enabled, created_at, updated_at
FROM scheduled_triggers
WHERE org_id = ? AND project_id = ?
ORDER BY created_at ASC
`

type ListScheduledTriggersByProjectParams struct {
	OrgID     string
	ProjectID string
}

func (q *Queries) ListScheduledTriggersByProject(ctx context.Context, arg ListScheduledTriggersByProjectParams) ([]ScheduledTrigger, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledTriggersByProject, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTrigger
	for rows.Next() {
		var i ScheduledTrigger
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.CronExpr,
			&i.Prompt,
			&i.NextAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledTrigger = `-- name: UpdateScheduledTrigger :exec
UPDATE scheduled_triggers
SET cron_expr = ?, prompt = ?, agent_id = ?, enabled = ?, next_at = ?, updated_at = ?
WHERE id = ? AND org_id = ?
`

type UpdateScheduledTriggerParams struct {
	CronExpr  string
	Prompt    string
	AgentID   string
	Enabled   int64
	NextAt    string
	UpdatedAt string
	ID        string
	OrgID     string
}

func (q *Queries) UpdateScheduledTrigger(ctx context.Context, arg UpdateScheduledTriggerParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduledTrigger,
		arg.CronExpr,
		arg.Prompt,
		arg.AgentID,
		arg.Enabled,
		arg.NextAt,
		arg.UpdatedAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}
