// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scim.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addSCIMGroupMember = `-- name: AddSCIMGroupMember :exec
INSERT INTO scim_group_members (group_id, user_id, org_id)
VALUES (?, ?, ?)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddSCIMGroupMemberParams struct {
	GroupID string
	UserID  string
	OrgID   string
}

func (q *Queries) AddSCIMGroupMember(ctx context.Context, arg AddSCIMGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addSCIMGroupMember, arg.GroupID, arg.UserID, arg.OrgID)
	return err
}

const clearSCIMGroupMembers = `-- name: ClearSCIMGroupMembers :exec
DELETE FROM scim_group_members
WHERE group_id = ? AND org_id = ?
`

type ClearSCIMGroupMembersParams struct {
	GroupID string
	OrgID   string
}

func (q *Queries) ClearSCIMGroupMembers(ctx context.Context, arg ClearSCIMGroupMembersParams) error {
	_, err := q.db.ExecContext(ctx, clearSCIMGroupMembers, arg.GroupID, arg.OrgID)
	return err
}

const countActiveSCIMTokens = `-- name: CountActiveSCIMTokens :one
SELECT count(*) FROM scim_tokens
WHERE org_id = ?1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > ?2)
`

type CountActiveSCIMTokensParams struct {
	OrgID string
	Now   sql.NullString
}

func (q *Queries) CountActiveSCIMTokens(ctx context.Context, arg CountActiveSCIMTokensParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSCIMTokens, arg.OrgID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMembershipOrgs = `-- name: CountUserMembershipOrgs :one
SELECT count(DISTINCT org_id) FROM memberships
WHERE actor_type = 'user' AND actor_id = ?
`

// How many orgs (any, including the platform org) the user still belongs to.
func (q *Queries) CountUserMembershipOrgs(ctx context.Context, actorID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserMembershipOrgs, actorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSCIMGroup = `-- name: CreateSCIMGroup :exec
INSERT INTO scim_groups (id, org_id, external_id, display_name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSCIMGroupParams struct {
	ID          string
	OrgID       string
	ExternalID  string
	DisplayName string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateSCIMGroup(ctx context.Context, arg CreateSCIMGroupParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMGroup,
		arg.ID,
		arg.OrgID,
		arg.ExternalID,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSCIMToken = `-- name: CreateSCIMToken :exec

INSERT INTO scim_tokens (id, org_id, name, prefix, token_hash, created_by, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSCIMTokenParams struct {
	ID        string
	OrgID     string
	Name      string
	Prefix    string
	TokenHash string
	CreatedBy string
	ExpiresAt sql.NullString
	CreatedAt string
}

// SCIM 2.0 provisioning (WU-611, SPEC s7.8). Every query binds org_id except
// FindSCIMTokenByPrefix, the bearer-token lookup: it maps a token prefix to
// its row, and the row's org_id is the org every later query is scoped to.
func (q *Queries) CreateSCIMToken(ctx context.Context, arg CreateSCIMTokenParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMToken,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSCIMUser = `-- name: CreateSCIMUser :exec
INSERT INTO scim_users (id, org_id, user_id, external_id, user_name, email, given_name, family_name,
                        display_name, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSCIMUserParams struct {
	ID          string
	OrgID       string
	UserID      string
	ExternalID  string
	UserName    string
	Email       string
	GivenName   string
	FamilyName  string
	DisplayName string
	Active      int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateSCIMUser(ctx context.Context, arg CreateSCIMUserParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMUser,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.ExternalID,
		arg.UserName,
		arg.Email,
		arg.GivenName,
		arg.FamilyName,
		arg.DisplayName,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSCIMGroup = `-- name: DeleteSCIMGroup :execrows
DELETE FROM scim_groups
WHERE id = ? AND org_id = ?
`

type DeleteSCIMGroupParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteSCIMGroup(ctx context.Context, arg DeleteSCIMGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMGroup, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSCIMUser = `-- name: DeleteSCIMUser :execrows
DELETE FROM scim_users
WHERE id = ? AND org_id = ?
`

type DeleteSCIMUserParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteSCIMUser(ctx context.Context, arg DeleteSCIMUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSCIMUser, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserOrgMemberships = `-- name: DeleteUserOrgMemberships :execrows
DELETE FROM memberships
WHERE org_id = ? AND actor_type = 'user' AND actor_id = ?
`

type DeleteUserOrgMembershipsParams struct {
	OrgID   string
	ActorID string
}

// SCIM deprovisioning: every membership of the user in one org, any source.
func (q *Queries) DeleteUserOrgMemberships(ctx context.Context, arg DeleteUserOrgMembershipsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserOrgMemberships, arg.OrgID, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findOrgMembershipForUser = `-- name: FindOrgMembershipForUser :one
SELECT id, org_id, actor_id, actor_type, resource_type, resource_id, role_id, created_at, source
FROM memberships
WHERE org_id = ?1 AND actor_type = 'user' AND actor_id = ?2
  AND resource_type = 'org' AND resource_id = ?1
`

type FindOrgMembershipForUserParams struct {
	OrgID   string
	ActorID string
}

func (q *Queries) FindOrgMembershipForUser(ctx context.Context, arg FindOrgMembershipForUserParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, findOrgMembershipForUser, arg.OrgID, arg.ActorID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorID,
		&i.ActorType,
		&i.ResourceType,
		&i.ResourceID,
		&i.RoleID,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const findSCIMTokenByPrefix = `-- name: FindSCIMTokenByPrefix :one
SELECT id, org_id, name, prefix, token_hash, expires_at, revoked_at
FROM scim_tokens
WHERE prefix = ?
`

type FindSCIMTokenByPrefixRow struct {
	ID        string
	OrgID     string
	Name      string
	Prefix    string
	TokenHash string
	ExpiresAt sql.NullString
	RevokedAt sql.NullString
}

func (q *Queries) FindSCIMTokenByPrefix(ctx context.Context, prefix string) (FindSCIMTokenByPrefixRow, error) {
	row := q.db.QueryRowContext(ctx, findSCIMTokenByPrefix, prefix)
	var i FindSCIMTokenByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const findSCIMUserByUserName = `-- name: FindSCIMUserByUserName :one
SELECT id, org_id, user_id, external_id, user_name, email, given_name, family_name, display_name, active, created_at, updated_at FROM scim_users
WHERE org_id = ? AND lower(user_name) = lower(?2)
`

type FindSCIMUserByUserNameParams struct {
	OrgID    string
	UserName string
}

func (q *Queries) FindSCIMUserByUserName(ctx context.Context, arg FindSCIMUserByUserNameParams) (ScimUser, error) {
	row := q.db.QueryRowContext(ctx, findSCIMUserByUserName, arg.OrgID, arg.UserName)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.ExternalID,
		&i.UserName,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmailFold = `-- name: FindUserByEmailFold :one
SELECT id, email, name, deleted_at
FROM users
WHERE lower(email) = lower(?1)
ORDER BY id
LIMIT 1
`

type FindUserByEmailFoldRow struct {
	ID        string
	Email     string
	Name      string
	DeletedAt sql.NullString
}

// Case-insensitive email lookup (SCIM provisioning and SCIM-linked sign-in).
func (q *Queries) FindUserByEmailFold(ctx context.Context, email string) (FindUserByEmailFoldRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmailFold, email)
	var i FindUserByEmailFoldRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgSSOSettingsForSCIM = `-- name: GetOrgSSOSettingsForSCIM :one
SELECT org_id, jit_default_role_id FROM org_sso_settings
WHERE org_id = ?
`

type GetOrgSSOSettingsForSCIMRow struct {
	OrgID            string
	JitDefaultRoleID sql.NullString
}

func (q *Queries) GetOrgSSOSettingsForSCIM(ctx context.Context, orgID string) (GetOrgSSOSettingsForSCIMRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgSSOSettingsForSCIM, orgID)
	var i GetOrgSSOSettingsForSCIMRow
	err := row.Scan(&i.OrgID, &i.JitDefaultRoleID)
	return i, err
}

const getSCIMGroup = `-- name: GetSCIMGroup :one
SELECT id, org_id, external_id, display_name, created_at, updated_at FROM scim_groups
WHERE id = ? AND org_id = ?
`

type GetSCIMGroupParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetSCIMGroup(ctx context.Context, arg GetSCIMGroupParams) (ScimGroup, error) {
	row := q.db.QueryRowContext(ctx, getSCIMGroup, arg.ID, arg.OrgID)
	var i ScimGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ExternalID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUser = `-- name: GetSCIMUser :one
SELECT id, org_id, user_id, external_id, user_name, email, given_name, family_name, display_name, active, created_at, updated_at FROM scim_users
WHERE id = ? AND org_id = ?
`

type GetSCIMUserParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetSCIMUser(ctx context.Context, arg GetSCIMUserParams) (ScimUser, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUser, arg.ID, arg.OrgID)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.ExternalID,
		&i.UserName,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSCIMUserByUser = `-- name: GetSCIMUserByUser :one
SELECT id, org_id, user_id, external_id, user_name, email, given_name, family_name, display_name, active, created_at, updated_at FROM scim_users
WHERE org_id = ? AND user_id = ?
`

type GetSCIMUserByUserParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) GetSCIMUserByUser(ctx context.Context, arg GetSCIMUserByUserParams) (ScimUser, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUserByUser, arg.OrgID, arg.UserID)
	var i ScimUser
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.ExternalID,
		&i.UserName,
		&i.Email,
		&i.GivenName,
		&i.FamilyName,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSCIMGroupMemberUsers = `-- name: ListSCIMGroupMemberUsers :many
SELECT user_id FROM scim_group_members
WHERE group_id = ? AND org_id = ?
`

type ListSCIMGroupMemberUsersParams struct {
	GroupID string
	OrgID   string
}

func (q *Queries) ListSCIMGroupMemberUsers(ctx context.Context, arg ListSCIMGroupMemberUsersParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroupMemberUsers, arg.GroupID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroupMembers = `-- name: ListSCIMGroupMembers :many
SELECT m.group_id, m.user_id, u.id AS scim_user_id, u.user_name
FROM scim_group_members m
JOIN scim_users u ON u.org_id = m.org_id AND u.user_id = m.user_id
WHERE m.org_id = ?
ORDER BY m.group_id, u.created_at, u.id
`

type ListSCIMGroupMembersRow struct {
	GroupID    string
	UserID     string
	ScimUserID string
	UserName   string
}

// Members of every group in the org, as SCIM user ids.
func (q *Queries) ListSCIMGroupMembers(ctx context.Context, orgID string) ([]ListSCIMGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroupMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSCIMGroupMembersRow
	for rows.Next() {
		var i ListSCIMGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.ScimUserID,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroups = `-- name: ListSCIMGroups :many
SELECT id, org_id, external_id, display_name, created_at, updated_at FROM scim_groups
WHERE org_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListSCIMGroups(ctx context.Context, orgID string) ([]ScimGroup, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroups, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimGroup
	for rows.Next() {
		var i ScimGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ExternalID,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMTokens = `-- name: ListSCIMTokens :many
SELECT id, org_id, name, prefix, created_by, expires_at, last_used_at, revoked_at, created_at
FROM scim_tokens
WHERE org_id = ?
ORDER BY created_at DESC, id
`

type ListSCIMTokensRow struct {
	ID         string
	OrgID      string
	Name       string
	Prefix     string
	CreatedBy  string
	ExpiresAt  sql.NullString
	LastUsedAt sql.NullString
	RevokedAt  sql.NullString
	CreatedAt  string
}

func (q *Queries) ListSCIMTokens(ctx context.Context, orgID string) ([]ListSCIMTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMTokens, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSCIMTokensRow
	for rows.Next() {
		var i ListSCIMTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMUserGroupNames = `-- name: ListSCIMUserGroupNames :many
SELECT g.display_name
FROM scim_group_members m
JOIN scim_groups g ON g.id = m.group_id AND g.org_id = m.org_id
WHERE m.org_id = ? AND m.user_id = ?
ORDER BY g.display_name
`

type ListSCIMUserGroupNamesParams struct {
	OrgID  string
	UserID string
}

// The display names of the SCIM groups user_id is in: the group values for
// reconciliation.
func (q *Queries) ListSCIMUserGroupNames(ctx context.Context, arg ListSCIMUserGroupNamesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMUserGroupNames, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMUsers = `-- name: ListSCIMUsers :many
SELECT id, org_id, user_id, external_id, user_name, email, given_name, family_name, display_name, active, created_at, updated_at FROM scim_users
WHERE org_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListSCIMUsers(ctx context.Context, orgID string) ([]ScimUser, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimUser
	for rows.Next() {
		var i ScimUser
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.ExternalID,
			&i.UserName,
			&i.Email,
			&i.GivenName,
			&i.FamilyName,
			&i.DisplayName,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSCIMGroupMember = `-- name: RemoveSCIMGroupMember :execrows
DELETE FROM scim_group_members
WHERE group_id = ? AND user_id = ? AND org_id = ?
`

type RemoveSCIMGroupMemberParams struct {
	GroupID string
	UserID  string
	OrgID   string
}

func (q *Queries) RemoveSCIMGroupMember(ctx context.Context, arg RemoveSCIMGroupMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeSCIMGroupMember, arg.GroupID, arg.UserID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeSCIMUserFromGroups = `-- name: RemoveSCIMUserFromGroups :exec
DELETE FROM scim_group_members
WHERE org_id = ? AND user_id = ?
`

type RemoveSCIMUserFromGroupsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) RemoveSCIMUserFromGroups(ctx context.Context, arg RemoveSCIMUserFromGroupsParams) error {
	_, err := q.db.ExecContext(ctx, removeSCIMUserFromGroups, arg.OrgID, arg.UserID)
	return err
}

const revokeSCIMToken = `-- name: RevokeSCIMToken :execrows
UPDATE scim_tokens SET revoked_at = ?1
WHERE id = ?2 AND org_id = ?3 AND revoked_at IS NULL
`

type RevokeSCIMTokenParams struct {
	Now   sql.NullString
	ID    string
	OrgID string
}

func (q *Queries) RevokeSCIMToken(ctx context.Context, arg RevokeSCIMTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSCIMToken, arg.Now, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserOrgAPIKeys = `-- name: RevokeUserOrgAPIKeys :execrows
UPDATE api_keys SET revoked_at = ?1
WHERE org_id = ?2 AND user_id = ?3 AND revoked_at IS NULL
`

type RevokeUserOrgAPIKeysParams struct {
	Now    sql.NullString
	OrgID  string
	UserID string
}

func (q *Queries) RevokeUserOrgAPIKeys(ctx context.Context, arg RevokeUserOrgAPIKeysParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserOrgAPIKeys, arg.Now, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSCIMToken = `-- name: TouchSCIMToken :exec
UPDATE scim_tokens SET last_used_at = ?1
WHERE id = ?2 AND org_id = ?3
  AND (last_used_at IS NULL OR last_used_at < ?4)
`

type TouchSCIMTokenParams struct {
	Now    sql.NullString
	ID     string
	OrgID  string
	Before sql.NullString
}

// Throttled: last_used_at moves at most once a minute.
func (q *Queries) TouchSCIMToken(ctx context.Context, arg TouchSCIMTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchSCIMToken,
		arg.Now,
		arg.ID,
		arg.OrgID,
		arg.Before,
	)
	return err
}

const updateSCIMGroup = `-- name: UpdateSCIMGroup :exec
UPDATE scim_groups SET external_id = ?, display_name = ?, updated_at = ?
WHERE id = ? AND org_id = ?
`

type UpdateSCIMGroupParams struct {
	ExternalID  string
	DisplayName string
	UpdatedAt   string
	ID          string
	OrgID       string
}

func (q *Queries) UpdateSCIMGroup(ctx context.Context, arg UpdateSCIMGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateSCIMGroup,
		arg.ExternalID,
		arg.DisplayName,
		arg.UpdatedAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateSCIMUser = `-- name: UpdateSCIMUser :exec
UPDATE scim_users SET external_id = ?, user_name = ?, email = ?, given_name = ?, family_name = ?,
    display_name = ?, active = ?, updated_at = ?
WHERE id = ? AND org_id = ?
`

type UpdateSCIMUserParams struct {
	ExternalID  string
	UserName    string
	Email       string
	GivenName   string
	FamilyName  string
	DisplayName string
	Active      int64
	UpdatedAt   string
	ID          string
	OrgID       string
}

func (q *Queries) UpdateSCIMUser(ctx context.Context, arg UpdateSCIMUserParams) error {
	_, err := q.db.ExecContext(ctx, updateSCIMUser,
		arg.ExternalID,
		arg.UserName,
		arg.Email,
		arg.GivenName,
		arg.FamilyName,
		arg.DisplayName,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}
