// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc)
VALUES (?, ?, ?, 1, ?, ?, ?, ?, ?)
RETURNING id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
`

type CreateSkillParams struct {
	ID                 string
	OrgID              sql.NullString
	Name               string
	Description        string
	Instructions       string
	AllowedActionsJson string
	ParamSchemaJson    string
	McpEndpointsEnc    string
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, createSkill,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.AllowedActionsJson,
		arg.ParamSchemaJson,
		arg.McpEndpointsEnc,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Instructions,
		&i.AllowedActionsJson,
		&i.ParamSchemaJson,
		&i.McpEndpointsEnc,
		&i.CreatedAt,
	)
	return i, err
}

const createSkillAtVersion = `-- name: CreateSkillAtVersion :one
INSERT INTO skills (id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
`

type CreateSkillAtVersionParams struct {
	ID                 string
	OrgID              sql.NullString
	Name               string
	Version            int64
	Description        string
	Instructions       string
	AllowedActionsJson string
	ParamSchemaJson    string
	McpEndpointsEnc    string
}

func (q *Queries) CreateSkillAtVersion(ctx context.Context, arg CreateSkillAtVersionParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, createSkillAtVersion,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Instructions,
		arg.AllowedActionsJson,
		arg.ParamSchemaJson,
		arg.McpEndpointsEnc,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Instructions,
		&i.AllowedActionsJson,
		&i.ParamSchemaJson,
		&i.McpEndpointsEnc,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = ? AND org_id = ?
`

type DeleteSkillParams struct {
	ID    string
	OrgID sql.NullString
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.ExecContext(ctx, deleteSkill, arg.ID, arg.OrgID)
	return err
}

const findLatestSkillByName = `-- name: FindLatestSkillByName :one
SELECT id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
FROM skills
WHERE org_id = ? AND name = ?
ORDER BY version DESC
LIMIT 1
`

type FindLatestSkillByNameParams struct {
	OrgID sql.NullString
	Name  string
}

func (q *Queries) FindLatestSkillByName(ctx context.Context, arg FindLatestSkillByNameParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, findLatestSkillByName, arg.OrgID, arg.Name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Instructions,
		&i.AllowedActionsJson,
		&i.ParamSchemaJson,
		&i.McpEndpointsEnc,
		&i.CreatedAt,
	)
	return i, err
}

const findMaxSkillVersion = `-- name: FindMaxSkillVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS INTEGER)
FROM skills
WHERE org_id = ? AND name = ?
`

type FindMaxSkillVersionParams struct {
	OrgID sql.NullString
	Name  string
}

func (q *Queries) FindMaxSkillVersion(ctx context.Context, arg FindMaxSkillVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findMaxSkillVersion, arg.OrgID, arg.Name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findSkillByID = `-- name: FindSkillByID :one
SELECT id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
FROM skills
WHERE id = ?
`

func (q *Queries) FindSkillByID(ctx context.Context, id string) (Skill, error) {
	row := q.db.QueryRowContext(ctx, findSkillByID, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Instructions,
		&i.AllowedActionsJson,
		&i.ParamSchemaJson,
		&i.McpEndpointsEnc,
		&i.CreatedAt,
	)
	return i, err
}

const findSkillByIDAndOrg = `-- name: FindSkillByIDAndOrg :one
SELECT id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
FROM skills
WHERE id = ? AND org_id = ?
`

type FindSkillByIDAndOrgParams struct {
	ID    string
	OrgID sql.NullString
}

func (q *Queries) FindSkillByIDAndOrg(ctx context.Context, arg FindSkillByIDAndOrgParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, findSkillByIDAndOrg, arg.ID, arg.OrgID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Instructions,
		&i.AllowedActionsJson,
		&i.ParamSchemaJson,
		&i.McpEndpointsEnc,
		&i.CreatedAt,
	)
	return i, err
}

const listPlatformSkills = `-- name: ListPlatformSkills :many
SELECT id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
FROM skills
WHERE org_id IS NULL
ORDER BY name ASC, version ASC
`

func (q *Queries) ListPlatformSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Instructions,
			&i.AllowedActionsJson,
			&i.ParamSchemaJson,
			&i.McpEndpointsEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillVersions = `-- name: ListSkillVersions :many
SELECT id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
FROM skills
WHERE org_id = ? AND name = ?
ORDER BY version ASC
`

type ListSkillVersionsParams struct {
	OrgID sql.NullString
	Name  string
}

func (q *Queries) ListSkillVersions(ctx context.Context, arg ListSkillVersionsParams) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkillVersions, arg.OrgID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Instructions,
			&i.AllowedActionsJson,
			&i.ParamSchemaJson,
			&i.McpEndpointsEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, org_id, name, version, description, instructions, allowed_actions_json, param_schema_json, mcp_endpoints_enc, created_at
FROM skills
WHERE org_id = ?
ORDER BY name ASC, version ASC
`

func (q *Queries) ListSkills(ctx context.Context, orgID sql.NullString) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkills, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Instructions,
			&i.AllowedActionsJson,
			&i.ParamSchemaJson,
			&i.McpEndpointsEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
