// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sprints.sql

package sqlc

import (
	"context"
)

const closeSprint = `-- name: CloseSprint :one
UPDATE sprints SET state = 'closed'
WHERE id = ? AND project_id = ?
RETURNING id, org_id, project_id, name, starts_on, ends_on, state, created_at
`

type CloseSprintParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) CloseSprint(ctx context.Context, arg CloseSprintParams) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, closeSprint, arg.ID, arg.ProjectID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (id, org_id, project_id, name, starts_on, ends_on, state)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, project_id, name, starts_on, ends_on, state, created_at
`

type CreateSprintParams struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	StartsOn  string
	EndsOn    string
	State     string
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, createSprint,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.State,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const findActiveSprint = `-- name: FindActiveSprint :one
SELECT id, org_id, project_id, name, starts_on, ends_on, state, created_at
FROM sprints
WHERE project_id = ? AND state = 'active'
ORDER BY starts_on DESC
LIMIT 1
`

func (q *Queries) FindActiveSprint(ctx context.Context, projectID string) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, findActiveSprint, projectID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const findSprint = `-- name: FindSprint :one
SELECT id, org_id, project_id, name, starts_on, ends_on, state, created_at
FROM sprints
WHERE id = ? AND project_id = ?
`

type FindSprintParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) FindSprint(ctx context.Context, arg FindSprintParams) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, findSprint, arg.ID, arg.ProjectID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const listSprints = `-- name: ListSprints :many
SELECT id, org_id, project_id, name, starts_on, ends_on, state, created_at
FROM sprints
WHERE project_id = ?
ORDER BY starts_on DESC
`

func (q *Queries) ListSprints(ctx context.Context, projectID string) ([]Sprint, error) {
	rows, err := q.db.QueryContext(ctx, listSprints, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sprint
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints SET name = ?, starts_on = ?, ends_on = ?, state = ?
WHERE id = ? AND project_id = ?
RETURNING id, org_id, project_id, name, starts_on, ends_on, state, created_at
`

type UpdateSprintParams struct {
	Name      string
	StartsOn  string
	EndsOn    string
	State     string
	ID        string
	ProjectID string
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRowContext(ctx, updateSprint,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.State,
		arg.ID,
		arg.ProjectID,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}
