// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, org_id, team_id, name, url, secret, event_filter, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, team_id, name, url, secret, event_filter, enabled, created_at, updated_at
`

type CreateWebhookParams struct {
	ID          string
	OrgID       string
	TeamID      sql.NullString
	Name        string
	Url         string
	Secret      string
	EventFilter string
	Enabled     int64
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ID,
		arg.OrgID,
		arg.TeamID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.EventFilter,
		arg.Enabled,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.EventFilter,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (id, webhook_id, event_name, event_json, status, max_attempts)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, webhook_id, event_name, event_json, status, attempts, max_attempts, response_code, error, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	ID          string
	WebhookID   string
	EventName   string
	EventJson   string
	Status      string
	MaxAttempts int64
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, createWebhookDelivery,
		arg.ID,
		arg.WebhookID,
		arg.EventName,
		arg.EventJson,
		arg.Status,
		arg.MaxAttempts,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventName,
		&i.EventJson,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ResponseCode,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks
WHERE id = ? AND org_id = ?
`

type DeleteWebhookParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, arg.ID, arg.OrgID)
	return err
}

const findWebhookByID = `-- name: FindWebhookByID :one
SELECT id, org_id, team_id, name, url, secret, event_filter, enabled, created_at, updated_at
FROM webhooks
WHERE id = ? AND org_id = ?
`

type FindWebhookByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) FindWebhookByID(ctx context.Context, arg FindWebhookByIDParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, findWebhookByID, arg.ID, arg.OrgID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.EventFilter,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWebhookDeliveryByID = `-- name: FindWebhookDeliveryByID :one
SELECT id, webhook_id, event_name, event_json, status, attempts, max_attempts, response_code, error, created_at, updated_at
FROM webhook_deliveries
WHERE id = ?
`

func (q *Queries) FindWebhookDeliveryByID(ctx context.Context, id string) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, findWebhookDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventName,
		&i.EventJson,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ResponseCode,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledWebhooksByOrg = `-- name: ListEnabledWebhooksByOrg :many
SELECT id, org_id, team_id, name, url, secret, event_filter, enabled, created_at, updated_at
FROM webhooks
WHERE org_id = ? AND enabled = 1
`

// Fetched by the delivery worker (WU-404): enabled webhooks in an org, used to
// match events against their event_filter.
func (q *Queries) ListEnabledWebhooksByOrg(ctx context.Context, orgID string) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledWebhooksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.EventFilter,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedWebhookDeliveries = `-- name: ListQueuedWebhookDeliveries :many
SELECT id, webhook_id, event_name, event_json, status, attempts, max_attempts, response_code, error, created_at, updated_at
FROM webhook_deliveries
WHERE status = 'queued' AND created_at <= ?
ORDER BY created_at ASC
`

// Polled by the delivery worker: queued deliveries due now.
func (q *Queries) ListQueuedWebhookDeliveries(ctx context.Context, createdAt string) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedWebhookDeliveries, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventName,
			&i.EventJson,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ResponseCode,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event_name, event_json, status, attempts, max_attempts, response_code, error, created_at, updated_at
FROM webhook_deliveries
WHERE webhook_id = ?
ORDER BY created_at DESC
LIMIT 100
`

// Delivery log for a webhook (delivery log UI).
func (q *Queries) ListWebhookDeliveries(ctx context.Context, webhookID string) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookDeliveries, webhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventName,
			&i.EventJson,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ResponseCode,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByOrg = `-- name: ListWebhooksByOrg :many
SELECT id, org_id, team_id, name, url, secret, event_filter, enabled, created_at, updated_at
FROM webhooks
WHERE org_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListWebhooksByOrg(ctx context.Context, orgID string) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.EventFilter,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByTeam = `-- name: ListWebhooksByTeam :many
SELECT id, org_id, team_id, name, url, secret, event_filter, enabled, created_at, updated_at
FROM webhooks
WHERE org_id = ? AND team_id = ?
ORDER BY created_at ASC
`

type ListWebhooksByTeamParams struct {
	OrgID  string
	TeamID sql.NullString
}

func (q *Queries) ListWebhooksByTeam(ctx context.Context, arg ListWebhooksByTeamParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByTeam, arg.OrgID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.EventFilter,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE webhooks
SET name = ?, url = ?, secret = ?, event_filter = ?, enabled = ?, updated_at = ?
WHERE id = ? AND org_id = ?
`

type UpdateWebhookParams struct {
	Name        string
	Url         string
	Secret      string
	EventFilter string
	Enabled     int64
	UpdatedAt   string
	ID          string
	OrgID       string
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhook,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.EventFilter,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateWebhookDeliveryAttempt = `-- name: UpdateWebhookDeliveryAttempt :exec
UPDATE webhook_deliveries
SET status = ?, attempts = ?, response_code = ?, error = ?, updated_at = ?
WHERE id = ?
`

type UpdateWebhookDeliveryAttemptParams struct {
	Status       string
	Attempts     int64
	ResponseCode sql.NullInt64
	Error        sql.NullString
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateWebhookDeliveryAttempt(ctx context.Context, arg UpdateWebhookDeliveryAttemptParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookDeliveryAttempt,
		arg.Status,
		arg.Attempts,
		arg.ResponseCode,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
